version: '3.1'
services:

  #PHP Service
  php:
    build:
      context: ./docker/php
      args:
      - WITH_XDEBUG=false
    volumes:
    - ./:/var/www/html

  #Nginx Service
  nginx:
    build: ./docker/nginx
    volumes:
    - ./:/var/www/html
    - ./docker/nginx/logs:/var/log/nginx


  #MySQL Service
  db:
    image: mysql:5.7
    volumes:
    - dbdata:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    - ./docker/mysql/logs:/var/log/mysql


#Volumes
volumes:
  dbdata:
