version: '3.1'
services:

  #PHP Service
  php:
    build:
      context: ./docker/php
      args:
      - WITH_XDEBUG=true
    container_name: php
    env_file: ./docker/php/.env
    volumes:
    - ./:/var/www/html

  #Nginx Service
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
    - "80:80"
    #    - "443:443"
    volumes:
    - ./:/var/www/html
    - ./docker/nginx/logs:/var/log/nginx


  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - dbdata:/var/lib/mysql
    - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    - ./docker/mysql/logs:/var/log/mysql


#Volumes
volumes:
  dbdata:
